sudo: false
language: python
python:
  - 3.5
  - 3.6
maxtrix:
  include:
    - python: 3.7
    dist: xenal
    sudo: true
install:
  - pip install poetry
  - poetry install -vvv
script:
  - poetry run
  - poetry run coverage run --source=tests -m pytest -v
#  - poetry run coveragge report -m
after_success:
#  - poetry run coveralls